-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 12:04:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_user` (
  `i_user_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `str_nickname` VARCHAR(45) NULL COMMENT '昵称\n',
  `str_unionid` VARCHAR(45) NULL COMMENT '微信得到的唯一ID\n',
  `d_balance` DOUBLE NULL COMMENT '324\n',
  `str_headurl` VARCHAR(45) NULL,
  UNIQUE INDEX `id_UNIQUE` (`i_user_id` ASC),
  PRIMARY KEY (`i_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_mteam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_mteam` (
  `i_img_url` INT NULL,
  `str_name` VARCHAR(45) NULL,
  `str_team_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`str_team_id`),
  UNIQUE INDEX `id_UNIQUE` (`str_team_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_schedule` (
  `i_schedule_id` INT NOT NULL,
  `str_team_id_1` VARCHAR(45) NULL,
  `str_team_id_2` VARCHAR(45) NULL,
  `data_time` DATETIME NULL COMMENT '比赛开始时间',
  `str_name` VARCHAR(45) NULL COMMENT '比赛名字,xx CUP BOx',
  `i_state` VARCHAR(45) NULL,
  PRIMARY KEY (`i_schedule_id`),
  UNIQUE INDEX `id_UNIQUE` (`i_schedule_id` ASC),
  INDEX `str_team_id_1_idx` (`str_team_id_1` ASC),
  INDEX `str_team_id_2_idx` (`str_team_id_2` ASC),
  CONSTRAINT `str_team_id_1`
    FOREIGN KEY (`str_team_id_1`)
    REFERENCES `mydb`.`t_mteam` (`str_team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `str_team_id_2`
    FOREIGN KEY (`str_team_id_2`)
    REFERENCES `mydb`.`t_mteam` (`str_team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_schedule_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_schedule_detail` (
  `schedule_detail_id` VARCHAR(45) NOT NULL,
  `detail_name` VARCHAR(45) NULL,
  `winner_id` VARCHAR(45) NULL,
  `team1_bet_amount` VARCHAR(45) NULL,
  `team2_bet_amount` VARCHAR(45) NULL,
  `t_schedule_i_schedule_id` INT NOT NULL,
  PRIMARY KEY (`schedule_detail_id`),
  INDEX `fk_t_schedule_detail_t_schedule1_idx` (`t_schedule_i_schedule_id` ASC),
  CONSTRAINT `fk_t_schedule_detail_t_schedule1`
    FOREIGN KEY (`t_schedule_i_schedule_id`)
    REFERENCES `mydb`.`t_schedule` (`i_schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_user_bet_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_user_bet_detail` (
  `bet_detail_id` INT NOT NULL,
  `bet_select` VARCHAR(45) NULL,
  `t_user_i_user_id` INT NOT NULL,
  `t_schedule_detail_schedule_detail_id` VARCHAR(45) NOT NULL,
  `i_bet_amount` INT NULL,
  PRIMARY KEY (`bet_detail_id`),
  INDEX `fk_t_user_bet_detail_t_user1_idx` (`t_user_i_user_id` ASC),
  INDEX `fk_t_user_bet_detail_t_schedule_detail1_idx` (`t_schedule_detail_schedule_detail_id` ASC),
  CONSTRAINT `fk_t_user_bet_detail_t_user1`
    FOREIGN KEY (`t_user_i_user_id`)
    REFERENCES `mydb`.`t_user` (`i_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_bet_detail_t_schedule_detail1`
    FOREIGN KEY (`t_schedule_detail_schedule_detail_id`)
    REFERENCES `mydb`.`t_schedule_detail` (`schedule_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_recharge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_recharge` (
  `i_recharge_id` INT NOT NULL,
  `data_time` DATETIME NULL,
  `i_amount` INT NULL,
  `t_user_i_user_id` INT NOT NULL,
  PRIMARY KEY (`i_recharge_id`),
  INDEX `fk_t_recharge_t_user_idx` (`t_user_i_user_id` ASC),
  CONSTRAINT `fk_t_recharge_t_user`
    FOREIGN KEY (`t_user_i_user_id`)
    REFERENCES `mydb`.`t_user` (`i_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
